version: '3.9'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend_wb:
    build:
      context: .
      dockerfile: Dockerfile
    image: whitebeauty:latest
    restart: always
    container_name: whitebeauty-dev
    depends_on:
      - db
    ports:
      - "8080:8000"
    volumes:
      - ./static:/wb/static
      - ./media:/wb/media

    command: >
      bash -c "source /home/adminuser/.venv/bin/activate && ./manage.py collectstatic --noinput && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 react_django.wsgi:application"

volumes:
  postgres_data:
  static:
  media:
